// <auto-generated />
using System;
using MGP.Location.Persistance.Data.Tables;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MGP.Location.Persistance.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240904190014_ProvincesSeed")]
    partial class ProvincesSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MGP.Location.Persistance.Data.Tables.Department", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("MGP.Location.Persistance.Data.Tables.Locality", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Locality");
                });

            modelBuilder.Entity("MGP.Location.Persistance.Data.Tables.Province", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<double>("CentroidLat")
                        .HasColumnType("double precision");

                    b.Property<double>("CentroidLon")
                        .HasColumnType("double precision");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("IsoId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("IsoName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Province");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Category = "Ciudad Autónoma",
                            CentroidLat = -34.614442065430097,
                            CentroidLon = -58.445876325091596,
                            FullName = "Ciudad Autónoma de Buenos Aires",
                            IsoId = "AR-C",
                            IsoName = "Ciudad Autónoma de Buenos Aires",
                            Name = "Ciudad Autónoma de Buenos Aires",
                            Source = "IGN"
                        },
                        new
                        {
                            Id = 58,
                            Category = "Provincia",
                            CentroidLat = -38.641982862667298,
                            CentroidLon = -70.119897223731797,
                            FullName = "Provincia del Neuquén",
                            IsoId = "AR-Q",
                            IsoName = "Neuquén",
                            Name = "Neuquén",
                            Source = "IGN"
                        },
                        new
                        {
                            Id = 74,
                            Category = "Provincia",
                            CentroidLat = -33.7611035381154,
                            CentroidLon = -66.025231271402106,
                            FullName = "Provincia de San Luis",
                            IsoId = "AR-D",
                            IsoName = "San Luis",
                            Name = "San Luis",
                            Source = "IGN"
                        },
                        new
                        {
                            Id = 82,
                            Category = "Provincia",
                            CentroidLat = -30.708822709152798,
                            CentroidLon = -60.950687276970598,
                            FullName = "Provincia de Santa Fe",
                            IsoId = "AR-S",
                            IsoName = "Santa Fe",
                            Name = "Santa Fe",
                            Source = "IGN"
                        },
                        new
                        {
                            Id = 46,
                            Category = "Provincia",
                            CentroidLat = -29.6849372775783,
                            CentroidLon = -67.181757581448693,
                            FullName = "Provincia de La Rioja",
                            IsoId = "AR-F",
                            IsoName = "La Rioja",
                            Name = "La Rioja",
                            Source = "IGN"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Provincia",
                            CentroidLat = -27.3359537960762,
                            CentroidLon = -66.947897245129496,
                            FullName = "Provincia de Catamarca",
                            IsoId = "AR-K",
                            IsoName = "Catamarca",
                            Name = "Catamarca",
                            Source = "IGN"
                        },
                        new
                        {
                            Id = 90,
                            Category = "Provincia",
                            CentroidLat = -26.948283501723001,
                            CentroidLon = -65.364765580368299,
                            FullName = "Provincia de Tucumán",
                            IsoId = "AR-T",
                            IsoName = "Tucumán",
                            Name = "Tucumán",
                            Source = "IGN"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Provincia",
                            CentroidLat = -26.386987183586701,
                            CentroidLon = -60.765116260356002,
                            FullName = "Provincia del Chaco",
                            IsoId = "AR-H",
                            IsoName = "Chaco",
                            Name = "Chaco",
                            Source = "IGN"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Provincia",
                            CentroidLat = -24.895087176148099,
                            CentroidLon = -59.932190112164697,
                            FullName = "Provincia de Formosa",
                            IsoId = "AR-P",
                            IsoName = "Formosa",
                            Name = "Formosa",
                            Source = "IGN"
                        },
                        new
                        {
                            Id = 78,
                            Category = "Provincia",
                            CentroidLat = -48.815547183052701,
                            CentroidLon = -69.955761914491305,
                            FullName = "Provincia de Santa Cruz",
                            IsoId = "AR-Z",
                            IsoName = "Santa Cruz",
                            Name = "Santa Cruz",
                            Source = "IGN"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Provincia",
                            CentroidLat = -43.788627138908303,
                            CentroidLon = -68.526736333981802,
                            FullName = "Provincia del Chubut",
                            IsoId = "AR-U",
                            IsoName = "Chubut",
                            Name = "Chubut",
                            Source = "IGN"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Provincia",
                            CentroidLat = -34.630388706716602,
                            CentroidLon = -68.582945601986694,
                            FullName = "Provincia de Mendoza",
                            IsoId = "AR-M",
                            IsoName = "Mendoza",
                            Name = "Mendoza",
                            Source = "IGN"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Provincia",
                            CentroidLat = -32.058927893855802,
                            CentroidLon = -59.201262616496003,
                            FullName = "Provincia de Entre Ríos",
                            IsoId = "AR-E",
                            IsoName = "Entre Ríos",
                            Name = "Entre Ríos",
                            Source = "IGN"
                        },
                        new
                        {
                            Id = 70,
                            Category = "Provincia",
                            CentroidLat = -30.865660701509601,
                            CentroidLon = -68.888159707177607,
                            FullName = "Provincia de San Juan",
                            IsoId = "AR-J",
                            IsoName = "San Juan",
                            Name = "San Juan",
                            Source = "IGN"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Provincia",
                            CentroidLat = -23.319975061658301,
                            CentroidLon = -65.764423919292,
                            FullName = "Provincia de Jujuy",
                            IsoId = "AR-Y",
                            IsoName = "Jujuy",
                            Name = "Jujuy",
                            Source = "IGN"
                        },
                        new
                        {
                            Id = 86,
                            Category = "Provincia",
                            CentroidLat = -27.783431881752101,
                            CentroidLon = -63.252626885646201,
                            FullName = "Provincia de Santiago del Estero",
                            IsoId = "AR-G",
                            IsoName = "Santiago del Estero",
                            Name = "Santiago del Estero",
                            Source = "IGN"
                        },
                        new
                        {
                            Id = 62,
                            Category = "Provincia",
                            CentroidLat = -40.405079630635903,
                            CentroidLon = -67.229675799603598,
                            FullName = "Provincia de Río Negro",
                            IsoId = "AR-R",
                            IsoName = "Río Negro",
                            Name = "Río Negro",
                            Source = "IGN"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Provincia",
                            CentroidLat = -28.7742044813623,
                            CentroidLon = -57.801081860333099,
                            FullName = "Provincia de Corrientes",
                            IsoId = "AR-W",
                            IsoName = "Corrientes",
                            Name = "Corrientes",
                            Source = "IGN"
                        },
                        new
                        {
                            Id = 54,
                            Category = "Provincia",
                            CentroidLat = -26.875302598903399,
                            CentroidLon = -54.651570562721901,
                            FullName = "Provincia de Misiones",
                            IsoId = "AR-N",
                            IsoName = "Misiones",
                            Name = "Misiones",
                            Source = "IGN"
                        },
                        new
                        {
                            Id = 66,
                            Category = "Provincia",
                            CentroidLat = -24.299283895720102,
                            CentroidLon = -64.814158657434604,
                            FullName = "Provincia de Salta",
                            IsoId = "AR-A",
                            IsoName = "Salta",
                            Name = "Salta",
                            Source = "IGN"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Provincia",
                            CentroidLat = -32.144799387385902,
                            CentroidLon = -63.801973466573003,
                            FullName = "Provincia de Córdoba",
                            IsoId = "AR-X",
                            IsoName = "Córdoba",
                            Name = "Córdoba",
                            Source = "IGN"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Provincia",
                            CentroidLat = -36.677392076082299,
                            CentroidLon = -60.5584771084959,
                            FullName = "Provincia de Buenos Aires",
                            IsoId = "AR-B",
                            IsoName = "Buenos Aires",
                            Name = "Buenos Aires",
                            Source = "IGN"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Provincia",
                            CentroidLat = -37.1350652212898,
                            CentroidLon = -65.447643999021295,
                            FullName = "Provincia de La Pampa",
                            IsoId = "AR-L",
                            IsoName = "La Pampa",
                            Name = "La Pampa",
                            Source = "IGN"
                        },
                        new
                        {
                            Id = 94,
                            Category = "Provincia",
                            CentroidLat = -82.521134521154494,
                            CentroidLon = -50.7428606764691,
                            FullName = "Provincia de Tierra del Fuego, Antártida e Islas del Atlántico Sur",
                            IsoId = "AR-V",
                            IsoName = "Tierra del Fuego",
                            Name = "Tierra del Fuego, Antártida e Islas del Atlántico Sur",
                            Source = "IGN"
                        });
                });

            modelBuilder.Entity("MGP.Location.Persistance.Data.Tables.Department", b =>
                {
                    b.HasOne("MGP.Location.Persistance.Data.Tables.Province", "Province")
                        .WithMany("Departments")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("MGP.Location.Persistance.Data.Tables.Locality", b =>
                {
                    b.HasOne("MGP.Location.Persistance.Data.Tables.Department", "Department")
                        .WithMany("Localities")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MGP.Location.Persistance.Data.Tables.Department", b =>
                {
                    b.Navigation("Localities");
                });

            modelBuilder.Entity("MGP.Location.Persistance.Data.Tables.Province", b =>
                {
                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
