// <auto-generated />
using System;
using MGP.Discapacidad.Persistance.Data.Tables;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MGP.Discapacidad.Persistance.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MGP.Discapacidad.Persistance.Data.Tables.CardPickupLocationsOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("CardPickupLocationsOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 538, DateTimeKind.Utc).AddTicks(8044),
                            Name = "Delegación Puerto - AYOLAS 3670"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 538, DateTimeKind.Utc).AddTicks(8048),
                            Name = "Sede Discapacidad - Pescadores 567"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 538, DateTimeKind.Utc).AddTicks(8049),
                            Name = "Delegación Sierra de Los Padres - Padre Luis Varetto 251"
                        });
                });

            modelBuilder.Entity("MGP.Discapacidad.Persistance.Data.Tables.CertificateExpansionOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("CertificateExpansionOption");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 538, DateTimeKind.Utc).AddTicks(8323),
                            Name = "No amplía"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 538, DateTimeKind.Utc).AddTicks(8325),
                            Name = "Agravamiento de Patología"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 538, DateTimeKind.Utc).AddTicks(8326),
                            Name = "Nueva Patología"
                        });
                });

            modelBuilder.Entity("MGP.Discapacidad.Persistance.Data.Tables.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentFullName")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("SentAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("ChatMessage");
                });

            modelBuilder.Entity("MGP.Discapacidad.Persistance.Data.Tables.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DocumentStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentStatusId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("TicketId");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("MGP.Discapacidad.Persistance.Data.Tables.DocumentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("DocumentStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 538, DateTimeKind.Utc).AddTicks(9950),
                            Name = "En espera de validación"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 538, DateTimeKind.Utc).AddTicks(9951),
                            Name = "Valido"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 538, DateTimeKind.Utc).AddTicks(9952),
                            Name = "Invalido"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 538, DateTimeKind.Utc).AddTicks(9953),
                            Name = "Eliminado"
                        });
                });

            modelBuilder.Entity("MGP.Discapacidad.Persistance.Data.Tables.DocumentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TicketTypeId");

                    b.ToTable("DocumentTemplate");
                });

            modelBuilder.Entity("MGP.Discapacidad.Persistance.Data.Tables.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("DocumentType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(167),
                            Name = "DNI Frente"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(168),
                            Name = "DNI Dorso"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(169),
                            Name = "DNI Frente/Madre/Tutor"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(170),
                            Name = "DNI Dorso/Madre/Tutor"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(171),
                            Name = "Recibo de Haberes"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(172),
                            Name = "Carnet Obra Social/Mutual/Prepaga"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(173),
                            Name = "Planilla Oficial"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(174),
                            Name = "Historia Clínica"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(175),
                            Name = "Estudio Complementario"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(175),
                            Name = "CUD"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(176),
                            Name = "Certificado de Extravio CUD"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(177),
                            Name = "Escritura del Domicilio / Contrato de Alquiler / Aval del Consorcio"
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(178),
                            Name = "Licencia de Conducir"
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(179),
                            Name = "Certificado de Cobertura del Seguro Automotor"
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(180),
                            Name = "Cédula del Vehículo"
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(181),
                            Name = "Croquis que Demarque el Frente de la Propiedad (Foto o Plano)"
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(182),
                            Name = "Foto 4x4"
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(182),
                            Name = "Certificado Extendido"
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(183),
                            Name = "Denuncia"
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(184),
                            Name = "DNI Conductor Frente"
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(185),
                            Name = "DNI Conductor Dorso"
                        });
                });

            modelBuilder.Entity("MGP.Discapacidad.Persistance.Data.Tables.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailHtml")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(361),
                            EmailHtml = "<!DOCTYPE html><html><head><meta charset='UTF-8'><style>body {font-family: Arial, sans-serif;color: #333;background-color: #f4f4f4;margin: 0;padding: 0;}.container {width: 100%;max-width: 600px;margin: auto;padding: 20px;background: #fff;border-radius: 8px;box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);}h1 {color: #0056b3;}.button {display: inline-block;padding: 10px 20px;font-size: 16px;color: #fff;background-color: #007bff;text-decoration: none;border-radius: 5px;margin-top: 20px;}.footer {margin-top: 20px;font-size: 14px;color: #777;text-align: center;}</style></head><body><div class='container'><h1>Solicitud de CUD</h1><p><strong>ESPERÁ QUE TE CONTACTE UN OPERADOR POR CORREO ELECTRÓNICO PARA ENVIARTE LA PLANILLA QUE CORRESPONDA E INDICARTE LOS ESTUDIOS QUE TENÉS QUE PRESENTAR. RECORDÁ QUE TANTO LOS ESTUDIOS COMO LAS PLANILLAS NO DEBEN SUPERAR LOS 12 MESES DE ANTIGÜEDAD. TENÉ EN CUENTA QUE LA RESPUESTA PUEDE DEMORAR HASTA 72 HORAS HÁBILES.</strong></p><p>Si no solicitaste este trámite, por favor ignora este mensaje.</p><div class='footer'><p>&copy; 2024 MDQ Digital. Todos los derechos reservados.</p></div></div></body></html>",
                            Name = "Template de Creación de CUD"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(362),
                            EmailHtml = "<!DOCTYPE html><html><head><meta charset='UTF-8'><style>body {font-family: Arial, sans-serif;color: #333;background-color: #f4f4f4;margin: 0;padding: 0;}.container {width: 100%;max-width: 600px;margin: auto;padding: 20px;background: #fff;border-radius: 8px;box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);}h1 {color: #0056b3;}.button {display: inline-block;padding: 10px 20px;font-size: 16px;color: #fff;background-color: #007bff;text-decoration: none;border-radius: 5px;margin-top: 20px;}.footer {margin-top: 20px;font-size: 14px;color: #777;text-align: center;}</style></head><body><div class='container'><h1>Solicitud de Tarjeta Sube</h1><p><strong>ESPERÁ QUE TE CONTACTE UN OPERADOR. TENÉ EN CUENTA QUE LA RESPUESTA PUEDE DEMORAR HASTA 72 HORAS HÁBILES.</strong></p><p>Si no solicitaste este trámite, por favor ignora este mensaje.</p><div class='footer'><p>&copy; 2024 MDQ Digital. Todos los derechos reservados.</p></div></div></body></html>",
                            Name = "Template de Creación de SUBE"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(363),
                            EmailHtml = "<!DOCTYPE html><html><head><meta charset='UTF-8'><style>body {font-family: Arial, sans-serif;color: #333;background-color: #f4f4f4;margin: 0;padding: 0;}.container {width: 100%;max-width: 600px;margin: auto;padding: 20px;background: #fff;border-radius: 8px;box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);}h1 {color: #0056b3;}.button {display: inline-block;padding: 10px 20px;font-size: 16px;color: #fff;background-color: #007bff;text-decoration: none;border-radius: 5px;margin-top: 20px;}.footer {margin-top: 20px;font-size: 14px;color: #777;text-align: center;}</style></head><body><div class='container'><h1>Solicitud de Estacionamiento</h1><p><strong>ESPERÁ QUE TE CONTACTE UN OPERADOR POR CHAT. TENÉ EN CUENTA QUE LA RESPUESTA PUEDE DEMORAR HASTA 72 HORAS HÁBILES.</strong></p><p>Si no solicitaste este trámite, por favor ignora este mensaje.</p><div class='footer'><p>&copy; 2024 MDQ Digital. Todos los derechos reservados.</p></div></div></body></html>",
                            Name = "Template de Creación de Parking"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(364),
                            EmailHtml = "<!DOCTYPE html><html><head><meta charset='UTF-8'><style>body {font-family: Arial, sans-serif;color: #333;background-color: #f4f4f4;margin: 0;padding: 0;}.container {width: 100%;max-width: 600px;margin: auto;padding: 20px;background: #fff;border-radius: 8px;box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);}h1 {color: #0056b3;}.button {display: inline-block;padding: 10px 20px;font-size: 16px;color: #fff;background-color: #007bff;text-decoration: none;border-radius: 5px;margin-top: 20px;}.footer {margin-top: 20px;font-size: 14px;color: #777;text-align: center;}</style></head><body><div class='container'><h1>HAY NOVEDADES DEL TRAMITE</h1><p><strong>Ingresá a MDQ Digital con tus credenciales para ver el estado de tu tramite: <a href='http://localhost:5173/' class='button'>Acceder</a></strong></p><p>Si no solicitaste este trámite, por favor ignora este mensaje.</p><div class='footer'><p>&copy; 2024 MDQ Digital. Todos los derechos reservados.</p></div></div></body></html>",
                            Name = "Nueva Actividad en Ticket"
                        });
                });

            modelBuilder.Entity("MGP.Discapacidad.Persistance.Data.Tables.SignatureOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("SignatureOption");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(488),
                            Name = "Firma realizada por la persona misma"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(489),
                            Name = "Firma realizada conjuntamente con otra persona"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(490),
                            Name = "Firma realizada por un tercero"
                        });
                });

            modelBuilder.Entity("MGP.Discapacidad.Persistance.Data.Tables.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedAgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GDECode")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("TicketStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TicketCode")
                        .IsUnique();

                    b.HasIndex("TicketStatusId");

                    b.HasIndex("TicketTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("MGP.Discapacidad.Persistance.Data.Tables.TicketCud", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Certificate")
                        .HasColumnType("boolean");

                    b.Property<int>("CertificateExpansionOptionsId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DocumentComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("ExpiredCertificate")
                        .HasColumnType("boolean");

                    b.Property<bool>("HealthInsurance")
                        .HasColumnType("boolean");

                    b.Property<bool>("LostCertificate")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("MedicalCommitteDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("PaySlip")
                        .HasColumnType("boolean");

                    b.Property<int>("SignatureOptionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CertificateExpansionOptionsId");

                    b.HasIndex("SignatureOptionId");

                    b.ToTable("TicketCud");
                });

            modelBuilder.Entity("MGP.Discapacidad.Persistance.Data.Tables.TicketParking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TicketParking");
                });

            modelBuilder.Entity("MGP.Discapacidad.Persistance.Data.Tables.TicketStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("TicketStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(613),
                            Name = "Nuevo"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(614),
                            Name = "En Proceso - Vecino"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(615),
                            Name = "En Proceso - Agente"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(658),
                            Name = "Esperando Resolución"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(659),
                            Name = "Cerrado por falta de Respuesta"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(660),
                            Name = "Cerrado Otorgado"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(660),
                            Name = "Cerrado denegado"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(661),
                            Name = "Cancelado"
                        });
                });

            modelBuilder.Entity("MGP.Discapacidad.Persistance.Data.Tables.TicketSube", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CardPickupId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CudCertificateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CudExpirationDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CardPickupId");

                    b.ToTable("TicketSube");
                });

            modelBuilder.Entity("MGP.Discapacidad.Persistance.Data.Tables.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("TicketType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(776),
                            Name = "CUD"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(777),
                            Name = "SUBE"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2024, 12, 12, 18, 49, 46, 539, DateTimeKind.Utc).AddTicks(778),
                            Name = "ESTACIONAMIENTO"
                        });
                });

            modelBuilder.Entity("MGP.Discapacidad.Persistance.Data.Tables.Document", b =>
                {
                    b.HasOne("MGP.Discapacidad.Persistance.Data.Tables.DocumentStatus", "DocumentStatus")
                        .WithMany()
                        .HasForeignKey("DocumentStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MGP.Discapacidad.Persistance.Data.Tables.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MGP.Discapacidad.Persistance.Data.Tables.Ticket", null)
                        .WithMany("Documents")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentStatus");

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("MGP.Discapacidad.Persistance.Data.Tables.DocumentTemplate", b =>
                {
                    b.HasOne("MGP.Discapacidad.Persistance.Data.Tables.TicketType", "TicketType")
                        .WithMany()
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("MGP.Discapacidad.Persistance.Data.Tables.Ticket", b =>
                {
                    b.HasOne("MGP.Discapacidad.Persistance.Data.Tables.TicketStatus", "TicketStatus")
                        .WithMany()
                        .HasForeignKey("TicketStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MGP.Discapacidad.Persistance.Data.Tables.TicketType", "TicketType")
                        .WithMany()
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TicketStatus");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("MGP.Discapacidad.Persistance.Data.Tables.TicketCud", b =>
                {
                    b.HasOne("MGP.Discapacidad.Persistance.Data.Tables.CertificateExpansionOptions", "CertificateExpansionOptions")
                        .WithMany()
                        .HasForeignKey("CertificateExpansionOptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MGP.Discapacidad.Persistance.Data.Tables.Ticket", "Ticket")
                        .WithOne()
                        .HasForeignKey("MGP.Discapacidad.Persistance.Data.Tables.TicketCud", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MGP.Discapacidad.Persistance.Data.Tables.SignatureOption", "SignatureOption")
                        .WithMany()
                        .HasForeignKey("SignatureOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CertificateExpansionOptions");

                    b.Navigation("SignatureOption");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("MGP.Discapacidad.Persistance.Data.Tables.TicketParking", b =>
                {
                    b.HasOne("MGP.Discapacidad.Persistance.Data.Tables.Ticket", "Ticket")
                        .WithOne()
                        .HasForeignKey("MGP.Discapacidad.Persistance.Data.Tables.TicketParking", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("MGP.Discapacidad.Persistance.Data.Tables.TicketSube", b =>
                {
                    b.HasOne("MGP.Discapacidad.Persistance.Data.Tables.CardPickupLocationsOptions", "CardPickupLocationsOptions")
                        .WithMany()
                        .HasForeignKey("CardPickupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MGP.Discapacidad.Persistance.Data.Tables.Ticket", "Ticket")
                        .WithOne()
                        .HasForeignKey("MGP.Discapacidad.Persistance.Data.Tables.TicketSube", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardPickupLocationsOptions");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("MGP.Discapacidad.Persistance.Data.Tables.Ticket", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
