services:
  authentication:
    build:
      context: .\MGP.Authentication.Api  # Esto indica el directorio actual como contexto de construcción
      dockerfile: Dockerfile  # El archivo Dockerfile específico que se usará
    image: mgp-authentication  # Nombre de la imagen que se construirá
    ports:
      - "5000:80"  # Exponer el puerto 80 del contenedor al puerto 5000 en el host